SHOW_FURIGANA = 'SHOW_FURIGANA';
SELECTED_STORIES = 'SELECTED_STORIES';
ENTRIES_LIMIT = 'ENTRIES_LIMIT';
ENTRIES_PER_PAGE = 10;

/* -------------------------------------------*/

Session.set(SHOW_FURIGANA, true);
Session.set(SELECTED_STORIES, []);
Session.set(ENTRIES_LIMIT, ENTRIES_PER_PAGE);